# Generated by Django 5.2.13 on 2026-04-21 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "catch_a_log_audit_log",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="catch_a_log_model_n_e121a2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoggingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("logger_name", models.CharField(db_index=True, max_length=255)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Not Set"),
                            (20, "Info"),
                            (30, "Warning"),
                            (10, "Debug"),
                            (40, "Error"),
                            (50, "Fatal"),
                            (50, "Critical"),
                        ],
                        db_index=True,
                    ),
                ),
                ("msg", models.TextField(blank=True)),
                ("args", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Logging Log",
                "verbose_name_plural": "Logging Logs",
                "db_table": "catch_a_log_logging_log",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="catch_a_log_created_1bc110_idx"
                    ),
                    models.Index(
                        fields=["logger_name", "created_at"],
                        name="catch_a_log_logger__db5cee_idx",
                    ),
                    models.Index(
                        fields=["level", "created_at"],
                        name="catch_a_log_level_5fdc11_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("username_persisted", models.CharField(blank=True, max_length=255)),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                ("host", models.CharField(db_index=True, max_length=255)),
                ("url", models.URLField()),
                ("path", models.CharField(db_index=True, max_length=1000)),
                ("method", models.CharField(max_length=10)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("headers", models.JSONField(default=dict, null=True)),
                ("cookies", models.JSONField(blank=True, default=dict)),
                ("body", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("remote_address", models.GenericIPAddressField(blank=True, null=True)),
                ("status_code", models.PositiveSmallIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("exception", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "db_table": "catch_a_log_request_log",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "requested_at"],
                        name="catch_a_log_user_id_c9bf14_idx",
                    ),
                    models.Index(
                        fields=["status_code", "requested_at"],
                        name="catch_a_log_status__5448e9_idx",
                    ),
                    models.Index(fields=["url"], name="catch_a_log_url_825ca5_idx"),
                ],
            },
        ),
    ]
